# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_pc_bttn = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn.setGeometry(QtCore.QRect(50, 30, 151, 23))
        self.add_pc_bttn.setObjectName("add_pc_bttn")
        self.add_pc_bttn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_2.setGeometry(QtCore.QRect(50, 70, 151, 23))
        self.add_pc_bttn_2.setObjectName("add_pc_bttn_2")
        self.add_pc_bttn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_3.setGeometry(QtCore.QRect(270, 70, 151, 23))
        self.add_pc_bttn_3.setObjectName("add_pc_bttn_3")
        self.add_pc_bttn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_4.setGeometry(QtCore.QRect(270, 30, 151, 23))
        self.add_pc_bttn_4.setObjectName("add_pc_bttn_4")
        self.add_pc_bttn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_5.setGeometry(QtCore.QRect(480, 30, 151, 23))
        self.add_pc_bttn_5.setObjectName("add_pc_bttn_5")
        self.add_pc_bttn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_6.setGeometry(QtCore.QRect(480, 70, 151, 23))
        self.add_pc_bttn_6.setObjectName("add_pc_bttn_6")
        self.add_pc_bttn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_7.setGeometry(QtCore.QRect(50, 110, 151, 23))
        self.add_pc_bttn_7.setObjectName("add_pc_bttn_7")
        self.add_pc_bttn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_8.setGeometry(QtCore.QRect(270, 110, 151, 23))
        self.add_pc_bttn_8.setObjectName("add_pc_bttn_8")
        self.add_pc_bttn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_9.setGeometry(QtCore.QRect(480, 110, 151, 23))
        self.add_pc_bttn_9.setObjectName("add_pc_bttn_9")
        self.add_pc_bttn_10 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_10.setGeometry(QtCore.QRect(50, 190, 151, 23))
        self.add_pc_bttn_10.setObjectName("add_pc_bttn_10")
        self.add_pc_bttn_11 = QtWidgets.QPushButton(self.centralwidget)
        self.add_pc_bttn_11.setGeometry(QtCore.QRect(270, 190, 151, 23))
        self.add_pc_bttn_11.setObjectName("add_pc_bttn_11")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_pc_bttn.setText(_translate("MainWindow", "Add PC"))
        self.add_pc_bttn_2.setText(_translate("MainWindow", "Add PRINTER"))
        self.add_pc_bttn_3.setText(_translate("MainWindow", "Add PHOTOCOPIER"))
        self.add_pc_bttn_4.setText(_translate("MainWindow", "Add SCANNER"))
        self.add_pc_bttn_5.setText(_translate("MainWindow", "Add PC_REPAIR"))
        self.add_pc_bttn_6.setText(_translate("MainWindow", "Add PC_UPDATE"))
        self.add_pc_bttn_7.setText(_translate("MainWindow", "Add ROUTER"))
        self.add_pc_bttn_8.setText(_translate("MainWindow", "Add PRINTER_REPAIR"))
        self.add_pc_bttn_9.setText(_translate("MainWindow", "Add PHOTOCOPIER_REPAIR"))
        self.add_pc_bttn_10.setText(_translate("MainWindow", "Add SCANNER_REPAIR"))
        self.add_pc_bttn_11.setText(_translate("MainWindow", "Add ROUTER_REPAIR"))
